# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6a524db2a4bd45dc788df324ffc9e6015c343742cfed265c83de7f7354bc20b91f1f8cb7e6b1e96738c515ce036719206750a2edbb22707ae368986addd994e

test:
  secret_key_base: d652f8d19095501766e05c44f26edd8c7153138b98d2a090acecbe2c31387a4a398870c0345b2184e0c58213351e2c7bc95ea694b6155945ccb55d9075b30ca2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
